# -*- coding: utf-8 -*-
"""Spectogram.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16RXKHbKI0Wh2B0kNQ_7IFOyZuSSEdpE2

# Spectogram example 1
from https://sanghyu.tistory.com/37
"""

import os
import numpy as np
import matplotlib.pyplot as plt

"""### install librosa
https://pypi.org/project/librosa/
"""

!pip install librosa

"""Visuallizing audio(.wav) in spectogram"""

import librosa
import librosa.display

sample_rate = 8000
n_fft = 512

x = librosa.load('test-weather.wav',16000)[0]
y = librosa.stft(x, n_fft=128, hop_length=64, win_length=128)

magnitude = np.abs(y)
log_spectrogram = librosa.amplitude_to_db(magnitude)

plt.figure(figsize=(10,4))
librosa.display.specshow(log_spectrogram, sr=16000, hop_length=64)
plt.xlabel("Time")
plt.ylabel("Frequency")
plt.colorbar(format='%+2.0f dB')
plt.title("Spectrogram (dB)")
